#!/usr/bin/env bash
# Install nginx on the server
# It should be listening on port 80
# When querying Nginx at its root / with a GET req using curl, it should 
# return a page that contains the string "Hello World!"

sudo apt update && sudo apt install nginx -y

sudo service start nginx

sudo ufw allow 'Nginx HTTP'
sudo CHOWN -R "$USER":"$USER" /var/www/html
sudo CHMOD -R 755 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

