#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default.conf
ln -sf /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf
service nginx restart
