#!/usr/bin/env bash
# Configure a nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf
sudo service nginx restart
