#!/usr/bin/env bash
# Dispalys the story of /etc/passwd lol

while IFS=':' read -r -a fields
do 
  echo -n "The user ${fields[0]} is part of the ${fields[3]} gang, "
  echo -n "lives in ${fields[5]} and rides ${fields[6]}. "
  echo -n "${fields[2]}'s place is protected by the passcode ${fields[1]},"
  echo "more info about the user here: ${fields[4]}"
done < "/etc/passwd"
