#!/usr/bin/env bash
#Bash using file test operators

file="school"
if [ -e $file ]; then
  echo "school file exists"

  # Check if the file is empty
  if [ -s $file ]; then
    echo "school file is not empty"

    # Check if the file is a regular file
    if [ -f $file ]; then
      echo "school is a regular file"
    fi
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi
