#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic

sudo apt-get update && sudo apt-get install ufw -y

sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw 80/tcp
