#!/usr/bin/env bash
# Bash script that uses ssh to connect to my server using private key
# ~/.shh/school with the user ubuntu

server="100.25.152.228"
private_key="~/.ssh/school"
user="ubuntu"

ssh -i $private_key $user
